//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace laba_5
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service
    {
        public int idServices { get; set; }
        public string NServices { get; set; }
        public decimal Price { get; set; }
        public byte[] image { get; set; }
    }
}
