//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace laba_5
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int idUser { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string MidleName { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public int idRole { get; set; }
        public byte[] Image { get; set; }
        public Nullable<int> diServices { get; set; }
    
        public virtual Role Role { get; set; }
        public virtual Service Service { get; set; }
    }
}
